# Generated by Django 2.2.2 on 2019-06-14 13:19

import accounts.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=50, verbose_name='Street')),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('pincode', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(999999)])),
                ('country', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(9999999999)], verbose_name='Mobile Number')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=11)),
                ('profile_pic', models.ImageField(upload_to='profile_pic', verbose_name='profile Picture')),
                ('dob', models.DateField(validators=[accounts.models.dob_validator], verbose_name='Date of birth')),
                ('company_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_address', to='accounts.Address')),
                ('permanent_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permanent_address', to='accounts.Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
