# Generated by Django 2.2.2 on 2019-06-14 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_address', to='accounts.Address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='permanent_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permanent_address', to='accounts.Address'),
        ),
    ]
