# Generated by Django 2.2.2 on 2019-06-14 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190614_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company_address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_address', to='accounts.Address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='permanent_address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permanent_address', to='accounts.Address'),
        ),
    ]
