# Generated by Django 2.2.2 on 2019-06-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_friends'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(null=True, related_name='_profile_friends_+', to='accounts.Profile'),
        ),
    ]
