# Generated by Django 2.2.2 on 2019-06-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190614_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='profile_pic', verbose_name='profile Picture'),
        ),
    ]
