# Generated by Django 2.2.2 on 2019-06-16 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190615_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_address', to='accounts.Address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='permanent_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permanent_address', to='accounts.Address'),
        ),
    ]
