# Generated by Django 2.2.2 on 2019-06-17 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20190616_2135'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('street', 'city', 'state', 'pincode', 'country')},
        ),
    ]
